name: doctor_app
description: A modern Doctor Patient Management App with SQLite local storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database (works on mobile + web)
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.3+1
  path: ^1.8.3

  # File & Image Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1

  # UI & Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
